spring:
  application:
    name: config-server
  profiles:
    active:
#   - git
    - native
  cloud:
    config:
      server:
        native:
          search-locations: 
          - classpath:/cofing/board          # github의 /board 내용
          - classpath:/config/license        # github의 /config 내용    
          - classpath:/config/organization   # 새롭게 추가
          - classpath:/config/discovery      # github의 /discovery 내용
          - classpath:/config/gateway
#         - file:///c:\temp\config
        git:
          uri: https://github.com/myanjini/license-service.git
          search-paths:
          - board
          - config
          - discovery
server:
  port: 8071
encrypt:
  key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo